"""Regression checks for card planes and branch preview ownership.

These test geometry invariants, not art quality. No production art is replaced
or generated by the synthetic alpha arrays used here.
"""
import unittest
import numpy as np
from cave_art_cards import raycast
from cave_card_junction import retirement_safe

def card(owner=None,yaw=0.,z=20.):
    return dict(asset='fixture',x=0.,y=-50.,z=z,width=100.,height=100.,
                uv=[0,0,1,1],yaw=yaw,owner_branch=owner)

class VisibilityTests(unittest.TestCase):
    alpha={'fixture':np.full((4,4),255,dtype=np.uint8)}
    portal=dict(z=14.,offset=1.85,half_width=.7,branches=[-1,0,1])

    def test_rotated_plane_depth_matches_analytic_intersection(self):
        for angle in (-.5,0.,.5):
            depth,_=raycast([card(yaw=angle,z=5.)],[.2,1.3,0.],(1,1),self.alpha,horizon=.5)
            self.assertAlmostEqual(depth[0,0],5.-.2*np.tan(angle),places=10)

    def test_behind_camera_card_cannot_occlude(self):
        depth,owner=raycast([card(z=-1.)],[0.,1.3,0.],(1,1),self.alpha,horizon=.5)
        self.assertTrue(np.isinf(depth).all());self.assertEqual(owner[0,0],-1)

    def test_partition_covers_view_without_sibling_overlap(self):
        cards=[card(b) for b in (-1,0,1)]
        depth,owner=raycast(cards,[0.,1.3,8.],(61,1),self.alpha,1552/830,
                            horizon=.5,portal=self.portal)
        self.assertTrue(np.isfinite(depth).all())
        self.assertEqual(set(owner.ravel()),{0,1,2})
        self.assertTrue(np.all(np.diff(owner[0])>=0))

    def test_do_not_retire_while_other_mouths_are_visible(self):
        self.assertFalse(retirement_safe(self.portal,[0.,1.3,12.],0))
        self.assertFalse(retirement_safe(self.portal,[0.,1.3,8.],None))

    def test_owner_ids_are_card_indices_not_branch_indices(self):
        # Deliberately mix card ordering with a shared, invisible first card.
        # A fixture containing just [-1,0,1] would conceal index aliasing.
        cards=[card(z=-1.),card(1),card(-1),card(0)]
        _,owner=raycast(cards,[0.,1.3,13.75],(31,1),self.alpha,1552/830,
                        horizon=.5,portal=self.portal,selected_branch=0)
        self.assertTrue(np.all(owner==3))

    def test_safe_retirement_preserves_first_hit(self):
        cards=[card(b) for b in (-1,0,1)]
        for b in (-1,0,1):
            pose=[b*1.85,1.78,13.75]
            self.assertTrue(retirement_safe(self.portal,pose,b,lens=.9545))
            full,owner=raycast(cards,pose,(61,19),self.alpha,1552/830,.9545,.37194,self.portal,b)
            short,_=raycast([cards[b+1]],pose,(61,19),self.alpha,1552/830,.9545,.37194,self.portal,b)
            np.testing.assert_array_equal(full,short)
            visible=owner[owner>=0]  # Ground is legitimately the first hit below the horizon.
            self.assertGreater(visible.size,0)
            self.assertTrue(np.all(visible==b+1))

    def test_gate_crossing_keeps_selected_identity(self):
        cards=[card(b) for b in (-1,0,1)]
        for z in (13.999,14.,14.001):
            _,owner=raycast(cards,[0.,1.3,z],(61,1),self.alpha,1552/830,
                            horizon=.5,portal=self.portal,selected_branch=0)
            self.assertTrue(np.all(owner==1))

if __name__=='__main__':unittest.main()
